name: Github Context

on:
 push:
 workflow_dispatch:
jobs:
 echo-context:
  runs-on: ubuntu-latest
  steps: 
   - name: Display Information
     run: |
      echo "Event name is ${{github.event_name}}"
      echo "Ref is ${{github.ref}}"
      echo "SHA is ${{github.SHA}}"
      echo "Actor is ${{github.actor}}"
      echo "Workflow is ${{github.workflow}}"
      echo "Run Id is ${{github.run_id}}"
      echo "Run number is ${{github.run_number}}"
