name: Matrix

on:
 workflow_dispatch:

jobs:
 echo-matrix:
  runs-on: ${{matrix.os}}
  strategy:
   matrix:
    node-version: [v22 ,v21]
    os: 
     - ubuntu-latest
     - windows-latest
  steps:
   -  uses: actions/setup-node@v4.2.0
      with:
       node-version: ${{matrix.node-version}}
   -   run: echo "Run in each os and node version ${{matrix.os}} and ${{matrix.node-version}}"
